# https://hub.docker.com/r/kvaps/letsencrypt-webroot/
version: "3.1"
services:

  stormy_nginx:
    restart: always
    image: nginx
    hostname: example.com
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./nginx:/etc/nginx:ro"
      - "./letsencrypt/conf:/etc/letsencrypt"
      - "./letsencrypt/html:/tmp/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@
  
  stormy_le:
    restart: always
    image: kvaps/letsencrypt-webroot
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt/conf:/etc/letsencrypt"
      - "./letsencrypt/html:/tmp/letsencrypt"
    links:
      - stormy_nginx:nginx
    environment:
      - DOMAINS=charlesreid1.blue www.charlesreid1.blue git.charlesreid1.blue charlesreid1.red www.charlesreid1.red git.charlesreid1.red
      - EMAIL=charles@charlesreid1.com
      - WEBROOT_PATH=/tmp/letsencrypt
      - EXP_LIMIT=30
      - CHECK_FREQ=30
