# https://hub.docker.com/r/kvaps/letsencrypt-webroot/
# https://github.com/dib-lab/wort/blob/master/docker-compose.yml
version: "3.1"
services:
  stormy_nginx:
    restart: always
    image: nginx
    hostname: charlesreid1.blue
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - "./nginx/:/etc/nginx/conf/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "./www:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
      - "443:443"
